alea/parameters.py, alea/statistical_model.py
See issue #43 -- if you do not set guesses manually, the error message is not easy to parse.
=> Check if some parameter is not set as guess when fitting

alea/model.py
Using best_fit_args is mostly relevant for 1D slices of higher-dimensional confidence volumes. 
In most cases, we want it to be set to confidence_interval_args. 
This PR sets it to confidence_interval_args, and makes the docstring more explicit. Also moves it to the last place in the argument list to emphasize that it is a rarer argument. 
What do you think about setting confidence_interval_args via kwargs instead?
=> Set best_fit_args to confidence_interval_args if None

alea/models/blueice_extended_model.py, alea/simulators.py, alea/template_source.py, docs/source/notebooks/placeholder.ipynb
This aims to allow runtime changing of livetime in data generation, get_expectation and likelihood evaluation. 
To test implementation: 
```
from alea.models.blueice_extended_model import BlueiceExtendedModel
model = BlueiceExtendedModel.from_config("/Users/kdund/Software/xenon_software/alea/alea/examples/configs/unbinned_wimp_statistical_model.yaml")
data = model.generate_data(er_rate_multiplier=1, wimp_rate_multiplier=1)
model.data = data
#get expectation value check: 
print(model.get_expectation_values(livetime_sr0=100, livetime_sr1=0))
print(model.get_expectation_values(livetime_sr0=1, livetime_sr1=0))
#1st is 100 times second
#likelihood evaluation check: 
ll_ratio = model.ll(livetime_sr0=1, er_rate_multiplier=1, wimp_rate_multiplier=0, livetime_sr1 = 0) / model.ll(livetime_sr0=10, …
```
=> Livetime scaling

alea/examples/configs/unbinned_wimp_running.yaml, alea/model.py, alea/models/blueice_extended_model.py, alea/runner.py, alea/submitter.py, alea/submitters/local.py, alea/utils.py, tests/test_runner.py, tests/test_utils.py
Resolve: https://github.com/XENONnT/alea/issues/83
Add optional argument `degree_of_freedom` for `asymptotic_critical_value`
1. For models, if `asymptotic_dof` is provided as an `__init__` argument, the `StatisticalModel.asymptotic_dof` will be used in `_confidence_interval_checks`.
2. For runners, if `asymptotic_dof` is in `statistical_model_args`, the `Runner.confidence_interval_thresholds` will be set according to `asymptotic_dof`, and further used in CL calculation.
```
from alea.utils import asymptotic_critical_value
asymptotic_critical_value("central", 0.9)
>>> 2.705543454095414
```
When `"confidence_interval_kind"` is not `"lower"` or `"upper"`, and `degree_of_freedom` is not `None` or 1, `asymptotic_critical_value` will raise an error.
_Please include the following if applicable:_
=> Add optional argument `degree_of_freedom` for `asymptotic_critical_value`

alea/runner.py
This PR adds the minuit convergence flag to the results. 
Closes #90 
Example to check: 
```
from alea.utils import load_yaml
from alea.runner import Runner
import numpy as np
runners = dict()
for fittable_sigma in [False, True]:
runner = Runner(
statistical_model = "alea.examples.gaussian_model.GaussianModel",
poi = "mu",
hypotheses = ["free","zero","true"],
n_mc = 100,
nominal_values = {"sigma":1.0},
generate_values = {"mu":1.0},
parameter_definition= {
"mu": {
"fit_guess": 0.0,
"fittable": True,
"nominal_value": 0.0,
"parameter_interval_bounds": [
-10,
10,
],
},
"sigma": {
"fittable": fittable_sigma,
"nominal_value": 1.0,
"fit_limits": [0,np.inf],
},
},
output_filename = "test_sigmafree_{:d}.hdf".format(int(fittable_sigma))
)
runner.run()
for sigma_free in [False, True]:
run_results = …
```
=> Add column to toyMC results with minuit convergence flag

alea/model.py, alea/parameters.py, alea/submitters/local.py
For shape parameters such as the WIMP mass, we haven't implemented anything that would allow resetting its nominal value after initialization. However, this is done to obtain the ``poi_rate_multiplier`` for a given ``poi_expectation``, which means that the poi_rate_multiplier values corresponding to a given threshold might be wrong in the end.
I did the following to fix this issue and prevent us from running into a similar issue in the future:
- Initialize a runner for each runner_arg in the ``NeymanConstructor``. This takes a bit longer and may sometimes be overkill but it works.
- Introduce a derived boolean property for a parameter called ``static`` (see #81 ), which is true if the parameter is
- not fittable
- neither a livetime nor rate (ptype)
- has no blueice anchors
- If one tries …
=> Update Neyman threshold when changing runner_args

alea/models/blueice_extended_model.py, tests/test_blueice_extended_model.py
This PR adds additional functionality to the `get_expectation_values` method in the `BlueiceExtendedModel`. By default, the expectation values for the same source are summed over all likelihood terms. This remains to be the default, however now you can also get a dict of a dict, which contains the expectation values for each lieklihood term individually.
```python
from alea import BlueiceExtendedModel
model = BlueiceExtendedModel.from_config("unbinned_wimp_statistical_model.yaml")
print(model.get_expectation_values())
print(model.get_expectation_values(per_likelihood_term=True))
```
=> Get expectation values per likelihood term

alea/utils.py, tests/test_utils.py
Without deepcopy, the dictionary inside returned list of function `convert_variations` will be entangled:
```
>>> convert_to_vary({"a": [1, 2], "b": [{"c": 3}, {"c": 4}]}) #  referred as `result`
[{'a': 1, 'b': {'c': 3}}, {'a': 1, 'b': {'c': 4}}, {'a': 2, 'b': {'c': 3}}, {'a': 2, 'b': {'c': 4}}]
```
When you modify the `result[0]['b']`, without this PR, `result[2]['b']` will also be changed, because only the address is shallowly copied.
This PR is split from https://github.com/XENONnT/alea/pull/103.
=> Prevent arguments to submission variations being changed by deepcopy-ing them. 

alea/model.py, alea/models/blueice_extended_model.py, alea/runner.py, alea/submitters/local.py, alea/utils.py
We do not need to initialize runner for each **{**nominal_values, **generate_values}, but we can read the poi directly from toymc files `output_filename`.
This was initially an idea from @hammannr, https://github.com/XENONnT/alea/pull/100#issuecomment-1784817837.
0. Save expectation_values to metadata
1. First figure out whether it is single `output_filename` mode or multiple(batch) `output_filename` mode
2. Read metadata from the list of `output_filename` and make sure that the metadata is the same in the list
3. Take the first entry of the metadata list as metadata
4. Assert it contains poi, which is guaranteed by https://github.com/XENONnT/alea/blob/80bd030205ed299fd26aedaddfdc31f3ee5849bb/alea/runner.py#L340
5. Read poi and expectation_values from metadata
6. Read poi_expectation from …
=> Read poi and expectation directly from `output_filename` to accelerate `NeymanConstructor`

alea/models/blueice_extended_model.py, tests/test_blueice_extended_model.py, tests/test_runner.py
Add function to get all sources names from all likelihoods in `BlueiceExtendedModel`
=> Add function to get all sources names from all likelihoods

alea/examples/configs/unbinned_wimp_statistical_model.yaml, alea/model.py, alea/models/blueice_extended_model.py, alea/parameters.py, tests/test_blueice_extended_model.py
As mentioned in #105 this PR improves the implementation of parameters that require the model to be re-initialized (such as the wimp_mass in case it is not treated as shape parameter.
For this, I added the `ptype` `"needs_reinit"`, which sets a related boolean property. The behaviour is then the same as before with the `static` boolean.
In the blueice extended model we now check that all ptypes are known and in case none are provided we fall back to needs_reinit.
=> Make sure values of parameters that need re-initialization are not changed

bin/alea-submission
#115 -- the world is rich, and we can allow any computation name (though "threshold" is special, and others such as "collate results" may be in the future)
=> Allow all computation names

alea/runner.py, alea/submitters/local.py
Because it is bool. Previously the `valid_fit` is a float.
=> Save dtype of `valid_fit` as bool

alea/runner.py
Provide `seed` as a keyword argument of `Runner`, so that we can reproduce the result when debugging because it is deterministic. In productive usage, it might not be necessary.
=> Optional setting of random seed for debugging

alea/submitter.py
Previously we only checked whether `output_filename` was made regardless of `only_toydata`, and did not checked `toydata_filename`.
In this PR, we check if:
1. `output_filename` is made when not `only_toydata`
2. `toydata_filename` is made when `toydata_mode` is `generate_and_store`
=> Improve check of already made toydata and output

alea/model.py, alea/submitter.py, alea/submitters/local.py, alea/submitters/slurm.py
Develop a new ticket generator: `combined_tickets_generator` which combines `combine_n_job` jobs into one by `" && "`.
Because the initialization of the container and environment will take some time, which is a constant offset proportional to the number of jobs. So this PR will reduce those time.
=> Combine several jobs into one to save computation resources

.gitignore, alea/examples/configs/unbinned_wimp_running.yaml, alea/runner.py
Previously only the `generate_values` are updated by `update_poi`:
https://github.com/XENONnT/alea/blob/cee1e71858fa967ecb00f123dc43d0c9b4127d91/alea/runner.py#L172-L181
This PR also updates `"poi_expectation"` in `hypotheses` and `common_hypothesis`.
=> Update `hypotheses` and `common_hypothesis` by `pre_process_poi`

README.md
Several look to alea to understand our signal or background model, this adds a short text to point out that alea takes this from otherwhere
=> point away from alea for physics models

alea/models/blueice_extended_model.py, alea/template_source.py
This PR makes `"piecewise"` the default pdf interpolation method. Before, the default was defined in blueice to `"linear"`, which is only in certain limits compatible with the `BlueiceDataGenerator`. The `BlueiceDataGenerator` is now only assigned if all sources have piecewise interpolation -- in the future we can add a suitable generator also for the linear interpolation case.
=> Make "piecewise" the default pdf interpolation

alea/template_source.py
So far, we only strictly enforced the lenghts of bin edges in config and template to match. I would suggest enforcing this also if values are off. In some cases the bin volumes are relevant and thus overriding the edges with wrong values might cause problems.
=> Enforce bins in config and template to match

alea/models/blueice_extended_model.py, alea/simulators.py, tests/test_blueice_extended_model.py, tests/test_template_source.py
This PR adds a method `get_source_histograms` to the `BlueiceExtendedModel`, which returns the pdfs/histograms of a specific likelihood term. Similar to `get_expectation_values` it accepts all kwargs and modifies the templates accordingly (closes #74).
To implement this, I use the `BlueiceDataGenerator` since it already has everything we need for this task.
After implementing this, I also rewrote `get_expectation_values` via the data generator. This avoids the workaround, which involved making a deepcopy of the entire class and generating fake data. This was also by far the slowest part so this implementation is now much faster than before. In addition, it benefits from the fact that the results for the last kwargs are always cached. So if I generate toy data and then want to check the …
=> Make model histograms accessible

alea/submitters/local.py
This small PR simply adds some useful information output when submitting with `--local --debug`.
In particular, it will print the parameter overview table and if available the nominal expectation values.
=> Make local submitter verbose

alea/utils.py, tests/test_utils.py
This PR adds a function to alea.utils that can estimate the best-fit signal multiplier given signal background model and data histogram. Compared to the iminuit fitting, it totally gets rid of the initial guess, which could cause fitting failure if it's too ridiculous. This function can be used as an initial guess of the multiplier when there are more nuisance parameters in the likelihood. The math is summarized [here](https://xe1t-wiki.lngs.infn.it/lib/exe/fetch.php?media=xenon:xenonnt:zihao:alea:signal_multiplier_estimator.pdf)
When testing it, it already gives quite good fit
To reproduce it,
```
import numpy as np
import multihist as mh
import matplotlib.pyplot as plt
import inference_interface as ii
from alea.utils import signal_multiplier_estimator
np.random.seed(1) …
```
=> Estimator of signal multiplier based on perturbation theory

alea/models/blueice_extended_model.py, tests/test_blueice_extended_model.py
@dachengx noticed that there is an inconsistency between the sorting when using `get_expectation_values()` and `get_source_histograms(...)`. This is not critical since only dictionaries are returned but can lead to confusion when looping through items.
This PR fixes this issue and sorts all returns by the source name.
=> Consistent sorting for BlueiceExtendedModel

alea/model.py, alea/utils.py, tests/test_blueice_extended_model.py
If toy data is already assigned to the model, it will be converted to `alea.utils.ReadOnlyDict`. So far, this type was not supported by the builtin `model.store_data()` method, which is changed with this PR.
Now you can:
```python
model = ...
model.data = model.generate_data()
model.store_data(file_name, [model.data])
```
=> Fixed data storing

alea/examples/configs/unbinned_wimp_statistical_model_index_fitting.yaml, alea/model.py, alea/models/blueice_extended_model.py, alea/utils.py, tests/test_blueice_extended_model.py
This PR modifies the default model.fit to support mixing continuous variables and index variables, with **little** extra time consuming. In this PR I only considered index variables as the shape parameter, i.e. a new ptype called `shape_index`. But the function can be easily used whenever we need other index variables in the future.
I did this because shape parameter usually causes many fitting problems since the likelihood can hardly be convex within the fitting limit if the shape parameter is not defined in a very careful way. Thus an alternative method is to do grid search on anchors as well as the `migrad()`. However if you simply do `migrad()` on all anchor points the computation speed will be significantly lowered. In this PR I do it in this way:
- Fix index variables to their …
=> Fitting index variables

alea/submitter.py
This is just a very small change for submission in debug mode.
It will print all parameter combinations that would be submitted, which can be helpful when using many `to_zip` and `to_vary`arguments.
=> Print Argument combinations to be submitted

alea/submitter.py, alea/submitters/local.py
The you can initialize the runner for `i_batch` toyMC:
```
submitter = SubmitterLocal.from_config(
config_path,
computation='sensitivity',
outputfolder=outputfolder,
debug=True,
resubmit=True,
i_batch=i_batch,
)
runner = submitter.submit()
```
For the `toydata_filename` in https://github.com/XENONnT/alea/blob/41119c7c2ec8f8438f9789d9c93911130d9cf8a1/alea/examples/configs/unbinned_wimp_running.yaml#L54 will be `toyfile_wimp_mass_50_poi_expectation_0.00.ii_2.h5` when `i_batch` is assigned to be 2.
=> Set `i_batch` for `SubmitterLocal` when submitting

alea/template_source.py, alea/utils.py
close: https://github.com/XENONnT/alea/issues/167
1. go through `likelihood_config`, for `str` in its values, try prefix template folder to them
2. go through every source in `likelihood_config_copy["sources"]`, for `str` in its values, try prefix template folder to them
=> Try prefix every file path in likelihood configuration with template folder

alea/utils.py
This is likely a bug introduced in #169. The original implementation was trying to prefix every field, as long as it happens to be an existing file after prefixing. You can see one example that this will lead to a problem.
Let's say you have defined the following sources in your statistical model yaml file:
```
- name: b8
histname: template
parameters:
- b8_rate_multiplier
- t_ly
- t_qy
named_parameters:
- t_ly
- t_qy
template_filename: cevns/template_XENONnT_sr0_cevns_cevns_tly_{t_ly:.1f}_tqy_{t_qy:.1f}.h5
- name: ac
histname: template
parameters:
- ac_rate_multiplier
template_filename: ac/template_XENONnT_sr0_ac_cevns.h5
```
in this example, with current alea it will complain a bug. In general, as long as your source name coincidence with a path name after prefixing, it will give an …
=> Forbid prexing every key when adapt_likelihood_config_for_blueice

tests/test_blueice_extended_model.py
Try to solve https://github.com/XENONnT/alea/issues/173
Use `np.testing.assert_almost_equal` to allow small numerical errors.
Close https://github.com/XENONnT/alea/issues/173 after merging
=> Try fixing https://github.com/XENONnT/alea/issues/173

alea/submitter.py, alea/submitters/local.py
For example, you might want to change the argument of runner on the fly, like:
```
submitter = SubmitterLocal.from_config(
ALEA_RUNNER_CONFIG_CL_PATH,
computation="sensitivity",
outputfolder="/project2/lgrandi/xudc/b8_unblindinding",
debug=True,
resubmit=True,
)
runner_68 = submitter.submit(confidence_level=0.6826894921370859)
runner_90 = submitter.submit(confidence_level=0.9)
```
`runner_68` calculates CL for 68% coverage, while `runner_90` is for 90% coverage.
=> Allow assigning kwargs in debug mode

alea/submitter.py
We should allow scanning `confidence_level` in runner configuratio `.yaml` file:
```
sensitivity:
to_vary:
{
t_ly: "np.linspace(0, 6, 7)",
confidence_level: [0.6827, 0.9],
}
```
Before this PR, you might see error like:
```
File "/home/xudc/alea/alea/submitter.py", line 352, in computation_tickets_generator
raise KeyError(
KeyError: "Keys for /home/xudc/out_alea/out_alea_b8_rate_exposure_scan/toymc_sensi_cevns_b8_rate_livetime_{livetime_sr
0:.2f}_{livetime_sr1:.2f}_b8_rate_{b8_rate_multiplier:.2f}_confidence_level_{confidence_level:.2f}_{i_batch:d}.h5 are 
not in provided arguments {'i_batch': 0, 'livetime_sr0': 1.174398, 'livetime_sr1': 0.0, 'b8_rate_multiplier': 1.0}, pl
ease check the output_filename."
```
=> Allow `confidence_level` in filename

alea/submitters/local.py
Straightforward implementation.
=> Add 68% coverage as one of the defaults of `confidence_levels`

alea/submitters/README.md
This is to fit the new situation on OSG, which forbids excessive CPU usage. Otherwise, typically error will be 
```
Excessive CPU usage. Please verify that the code is configur
ed to use a limited number of cpus/threads, and matches request_cpus.
```
However, I didn't figure out how many threads do `alea-run_toymc` is trying to open. I just put an empirical 4 here for now. Still testing...
=> Document to increase CPUs

alea/examples/configs/unbinned_wimp_statistical_model.yaml, alea/examples/configs/unbinned_wimp_statistical_model_template_source_test.yaml, alea/models/blueice_extended_model.py
This will kill the pain when people forget about `apply_efficiency`.
=> Defunctionalize `apply_efficiency`, apply efficiency when `efficiency_name` is specified

.github/workflows/pypi_install.yml
For v0.2.4 and v0.2.5, the PyPI workflow was not triggered, probably because I saved the release as a draft before publishing it. Since we currently trigger the workflow on `created`, this is the intended behaviour as stated [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release). So solve this, I suggest triggering on `published` in the future (trigger on the following: "A release, pre-release, or draft of a release was published.").
=> Trigger PyPI workflow on "published"

alea/examples/configs/unbinned_wimp_statistical_model_mass_dependent_efficiency.yaml, alea/parameters.py, tests/test_parameters.py
This PR introduces conditional parameters.
In some cases, we want parameters to take different values depending on the value of other parameters.
One example is the WIMP-mass-dependent signal efficiency uncertainty. Here, we typically have larger uncertainties for lower masses. With conditional parameters, we can now simply add the following to our parameter definition in the config file:
```
wimp_mass:
nominal_value: 50
...
signal_efficiency:
conditioning_parameter_name: wimp_mass
uncertainty:
5: 0.3
10: 0.2
50: 0.15
100: 0.1
500: 0.1
...
```
Depending on the value of `wimp_mass` this will result in a different value of the `signal_efficiency` uncertainty.
Here's an example how the ConditionalParameter class works:
```python
from alea import load_yaml, Parameters
config_path = …
```
=> Conditional Parameters

alea/utils.py, tests/test_blueice_extended_model.py
Turns out the `apply_efficiency` key, which was removed in #183 had a reason. It is propagated to blueice [here](https://github.com/JelleAalbers/blueice/blob/f12c2adffc0698e874a5fa25cbb7436fc5c58d54/blueice/likelihood.py#L83). If it is not provided, the efficiency is correctly added to the alea likelihood (since #183) but not taken into account in the likelihood evaluation.
This PR fixes this by automatically adding the key to the blueice config in case a `efficiency_name` is provided.
=> Fix apply efficiency

alea/examples/configs/unbinned_wimp_running.yaml, alea/examples/configs/unbinned_wimp_statistical_model.yaml, alea/model.py, alea/runner.py, alea/submitter.py
In the past, we observed that sometimes, and under certain conditions, minuit might not find a "valid" minimum for the fit. There are a few different solutions to this issue:
* Continue the fit with higher precision
* Use a different minimizer routine to begin with
* Increase fit precision to begin with
In this PR, we enable choosing a fit strategy. For this, we add `_fit_strategy` attribute to the `StatisticalModel` class, which is used in the `fit()` and `confidence_interval()` method if not specified otherwise.
The `_fit_strategy` is a dictionary with the following entries:
| Entry | Functionality | Options |
|:-----|:---|:---|
|`minimizer_routine` (Default: `"migrad"`) | the minimizer routine to use | "migrad", "simplex", or "simplex_migrad" (first run simplex, then migrad) | …
=> Enable choosing the fit strategy

alea/submitters/run_toymc_wrapper.sh
In #182  we added `fit_strategy` as an argument to the runner. Unfortunately, I missed to also add it to the shell script, which is called for submissions to OSG, which led to shifted arguments. This PR should fix the mismatch.
=> Fix OSG submission

alea/submitters/htcondor.py
Thanks @dachengx for catching this. This is not used anywhere and the functionality has been fully covered by [this](https://github.com/XENONnT/alea/blob/1789e908537c9173bfa2ab16c503f3df4057d9a6/alea/submitters/htcondor.py#L267.).
=> Removed deprecated `_pegasus_properties`

alea/submitters/htcondor.py
- for memory, the unit is MB
- for disk, the unit is KB
=> There was a typo in docstr

alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh
=> Prefer f-string than format

alea/submitters/htcondor.py
Close: https://github.com/XENONnT/alea/issues/194
Change `SubmitterHTCondor.generated_dir`, `SubmitterHTCondor.runs_dir`, and `SubmitterHTCondor.outputs_dir`. Add `SubmitterHTCondor.scratch_dir`.
=> Use tree structure work directory

alea/submitters/README.md, alea/submitters/htcondor.py
More than https://github.com/XENONnT/alea/pull/198
[slack thread](https://xenonnt.slack.com/archives/C04JRF0AZTP/p1725488333322409) (internal reference)
=> Use MB all the time in `SubmitterHTCondor`, no more kB

alea/submitters/README.md, alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh, alea/submitters/separate.sh
1. Add bash script `alea/submitters/separate.sh` which decompresses the output of each `combine.sh` job locally.
2. Add function `_add_separate_job` which calls with `run_on_submit_node = True` to run the decompression locally.
3. Replace most `.format` to f-string (minor change)
Close: https://github.com/XENONnT/alea/issues/175
Reference: https://pegasus.isi.edu/documentation/index.html
=> Decompress outputs into `outputfolder`

alea/submitters/combine.sh, alea/submitters/htcondor.py, alea/submitters/slurm.py
Close: https://github.com/XENONnT/alea/issues/203
=> Save log for OSG jobs

alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh
Otherwise, we might see a problem when interpreting the inputs for `alea/submitters/run_toymc_wrapper.sh`.
=> Use `shlex.quote` to convert the arguments into unix format

alea/submitters/README.md, alea/submitters/htcondor.py
Depends on https://github.com/XENONnT/utilix/pull/124.
=> Use utilix to validate X509 proxy

alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh, alea/utils.py
as long as their names are different
Asking all templates are in the same folder does not make sense, configuration like: https://github.com/XENONnT/nton/blob/fcccf25d583e1ee218724c4962d6fac9583c5191/nton/wimp/configs/sr0_sr1/wimp_statistical_model_ac_optimization.yaml#L409 and https://github.com/XENONnT/nton/blob/fcccf25d583e1ee218724c4962d6fac9583c5191/nton/wimp/configs/sr0_sr1/wimp_statistical_model_ac_optimization.yaml#L553 should be allowed.
1. Add a class `LockableSet` and initialize a variable `TEMPLATE_RECORDS` in `alea/utils.py`
2. Update `TEMPLATE_RECORDS` in `alea.utils._prefix_file_path`, so `TEMPLATE_RECORDS` will record all needed templates absolute path
3. Then we do not need `alea.submitters.htcondor.SubmitterHTCondor._validate_template_path` or …
=> Tarball all needed templates from different folder

alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh
A further fix of https://github.com/XENONnT/alea/pull/210.
=> Fix the path of `alea_run_toymc` script

alea/submitters/htcondor.py, alea/submitters/install.sh, alea/submitters/run_toymc_wrapper.sh
Similar to https://github.com/XENONnT/outsource/pull/175
=> Tarball alea for later user installation

alea/submitters/htcondor.py
Close: https://github.com/XENONnT/alea/issues/221
Remove `self.scratch_dir` because it is not needed. Generally speaking, for pegasus workflow building we only need a single `Directory.SHARED_SCRATCH` and a single `Directory.LOCAL_STORAGE`.
=> Keep only one `Directory.SHARED_SCRATCH`

alea/submitters/htcondor.py
Reverts XENONnT/alea#222
So my statement in the previous PR is incorrect: https://github.com/XENONnT/alea/pull/222#issue-2560049008.
Otherwise, we will see errors when job submission like:
```
Pegasus.client._client.PegasusClientError: Pegasus command: ['/usr/bin/pegasus-plan', '-Dpegasus.metrics.app=XENON', '-Dpegasus.data.configuration=nonsharedfs', '-Ddagman.retry=0', '-Ddagman.maxidle=100000', '-Ddagman.maxjobs=100000', '-Dpegasus.transfer.threads=4', '-Dpegasus.monitord.encoding=json', '-Dpegasus.catalog.workflow.amqp.url=amqp://friend:donatedata@msgs.pegasus.isi.edu:5672/prod/workflows', '--cluster', 'horizontal', '--sites', 'condorpool', '--output-sites', 'local', '--staging-site', 'condorpool=staging-davs', '--dir', '/scratch/xudc/workflows/wimp_ac_optimization-discovery_power-2024 …
```
=> Revert "Keep only one `Directory.SHARED_SCRATCH`"

alea/submitters/htcondor.py
This will prevent output/scratch files related to different workflows putting in the same folder and being hard to distinguish.
Suggested in [slack thread](https://xenonnt.slack.com/archives/C048FE2U3KN/p1727117756578409?thread_ts=1726926843.149369&cid=C048FE2U3KN), sorry it has only internal access.
=> Add the workflow id to the folder in staging-davs

alea/models/blueice_extended_model.py
This fixes a very dumb bug in the `get_expectation_value` method of the `BlueiceExtendedModel`. So far, the lifetime was popped from the `generate_values`, which meant that if two or more terms used the same livetime parameter, the value would only be used for the first one.
=> Fix livetime bug in get_expectation_values()

alea/template_source.py, alea/utils.py, tests/test_template_source.py
So far, if you made changes to a template that was already cached by blueice, blueice would use the cached version instead of the new one. This PR solves this issue by computing the hash of each source's template file and adding it to the blueice source config.
=> Add file hash to blueice hash

alea/submitters/local.py
This is just a tiny improvement to make the error message of a metadata mismatch in the `NeymanConstructor` more useful for checking which files to look into.
=> Make metadata error message more informative

alea/models/blueice_extended_model.py
This is another tiny PR to improve the template caching behavior.
So far, we specify all `shape` and `index` parameters that are not used by a source in the `dont_hash_settings`. However, wit this we're missing shape parameters such as the WIMP mass, which is usually implemented as a `needs_reinit` parameter. By including it now we can reduce the number of duplicated cached histograms.
=> Add unused needs_reinit parameters to ignored parameters

alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh
Similar to alea, this now tars and installs a user-installed version of blueice to osg computing nodes.
=> Tar user-installed blueice to osg nodes

alea/models/blueice_extended_model.py
Enables (and defaults to) source-wise interpolation, which is introduced in [blueice PR46](https://github.com/JelleAalbers/blueice/pull/46).
Let's wait with this PR until the blueice PR is done but I'll put this here in case anyone wants to already give it a try!
=> Source-wise interpolation

alea/submitters/htcondor.py
Otherwise, you will see error like:
```
Traceback (most recent call last):
File "/home/xudc/alea/alea/scripts/alea_submission.py", line 99, in <module>
main()
File "/home/xudc/alea/alea/scripts/alea_submission.py", line 95, in main
submitter.submit()
File "/home/xudc/alea/alea/submitters/htcondor.py", line 700, in submit
self._generate_workflow()
File "/home/xudc/alea/alea/submitters/htcondor.py", line 585, in _generate_workflow
job.add_inputs(
File "/usr/lib64/pegasus/python/Pegasus/api/_utils.py", line 85, in wrapper
assert f(self, *args, **kwargs) == None
File "/usr/lib64/pegasus/python/Pegasus/api/workflow.py", line 88, in add_inputs
raise DuplicateError(
Pegasus.api.errors.DuplicateError: file: alea.tar.gz has already been added as input to this job
```
=> Fix bug, only add tarball when git installed

alea/examples/configs/unbinned_wimp_statistical_model_index_fitting.yaml, alea/models/blueice_extended_model.py, pyproject.toml
This updates blueice dependence to require version 1.2.1, which includes the source-wise interpolation.
=> Update blueice dependence

alea/models/blueice_extended_model.py
Currently, the sources don't know which likelihood they are in, as this information is not passed to the `pdf_base_config`
Adding this information is helpful in the cases when we want to apply specific treatment to each source when the likelihood names are different (for example sr0 and sr1)
=> Parse the likelihood name to the base config

alea/runner.py, alea/submitters/htcondor.py, alea/submitters/run_toymc_wrapper.sh
This PR introduces two modifications to enhance flexibility and correctness when handling CES jobs and POI configurations:
---
- **Context**: In CES jobs, some sources use a mixed spectrum composed as a weighted average of multiple histograms.
- **Issue**: The `template_filenames` field can be a list rather than a single string, but the original `update_template_filenames()` function did not support this.
- **Solution**: The function now checks if the value is a list and applies `os.path.basename()` to each entry. This ensures consistent filename extraction for both string and list inputs.
---
- **Context**: The original POI logic assumes the POI is the absolute number of observed events (used in WIMP searches).
- **Issue**: For CES studies, the expected event count is normalized …
=> Modifications to Enable OSG Submissions for CES Jobs

alea/runner.py, alea/submitters/run_toymc_wrapper.sh
In #255 we had two modifications to enable the support for CES job submissions on OSG. But thanks to @dachengx, I now realize that the `poi_is_rate_multiplier` is redundant. The use of `poi` is just a special case in the WIMP config. More generally, we can set `generate_values` directly in the config to change the rate multipliers directly. 
Thererfore, we revert the changes for the `poi_is_rate_multiplier` implementation, while keeping the handling for `template_filenames`
=> Revert poi rate multiplier and toymc wrapper changes
